CREATE TABLE
	public.playlist (
		id int8 GENERATED BY DEFAULT AS IDENTITY (
			INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE
		) NOT NULL,
		created_at timestamptz DEFAULT now () NOT NULL,
		created_by text NULL,
		title text NULL,
		url text NULL,
		thumbnail text NULL,
		artist text NULL,
		artist_image text NULL,
		duration text NULL,
		CONSTRAINT playlist_pkey PRIMARY KEY (id)
	);