CREATE TABLE 
    public.songs (
        id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
        created_at timestamptz DEFAULT now() NOT NULL,
        url text NOT NULL,
        note text NULL,
        status int2 DEFAULT '-2'::smallint NULL,
        title text NULL,
        duration text NULL,
        thumbnail text NULL,
        artist text NULL,
        artist_image text NULL,
        created_by text NULL,
        created_name text NULL,
        video_id text NULL,
        CONSTRAINT songs_id_key UNIQUE (id),
        CONSTRAINT songs_pkey PRIMARY KEY (id)
    );
CREATE INDEX songs_url_stat_created_at_idx ON public.songs USING btree (url, status, created_at);